// <auto-generated />
using GoxuTour.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoxuTour.Persistence.Migrations
{
    [DbContext(typeof(GoxuTourDbContext))]
    partial class GoxuTourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoxuTour.Domain.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusModelId")
                        .HasColumnType("int");

                    b.Property<int>("DistanceTraveled")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationPlate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SeatMapping")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BusModelId");

                    b.ToTable("buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 GRB 22",
                            SeatMapping = 1,
                            Year = (short)1998
                        },
                        new
                        {
                            Id = 2,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 LTF 22",
                            SeatMapping = 3,
                            Year = (short)1999
                        },
                        new
                        {
                            Id = 3,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 KAYA 22",
                            SeatMapping = 2,
                            Year = (short)1997
                        },
                        new
                        {
                            Id = 4,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 GKS 22",
                            SeatMapping = 2,
                            Year = (short)1998
                        },
                        new
                        {
                            Id = 5,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 UMT 22",
                            SeatMapping = 3,
                            Year = (short)1994
                        },
                        new
                        {
                            Id = 6,
                            BusModelId = 2,
                            DistanceTraveled = 600,
                            RegistrationPlate = "34 EMRE 22",
                            SeatMapping = 1,
                            Year = (short)1984
                        });
                });

            modelBuilder.Entity("GoxuTour.Domain.BusManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("busManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wolksvagen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FIAT"
                        },
                        new
                        {
                            Id = 5,
                            Name = "MAN"
                        });
                });

            modelBuilder.Entity("GoxuTour.Domain.BusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusManufacturerId")
                        .HasColumnType("int");

                    b.Property<bool>("HasToilet")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusManufacturerId");

                    b.ToTable("busModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusManufacturerId = 1,
                            HasToilet = true,
                            Name = "Travego",
                            SeatCapacity = 44,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            BusManufacturerId = 2,
                            HasToilet = true,
                            Name = "Neoplan",
                            SeatCapacity = 44,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            BusManufacturerId = 3,
                            HasToilet = false,
                            Name = "Connecto",
                            SeatCapacity = 44,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            BusManufacturerId = 4,
                            HasToilet = true,
                            Name = "Travego",
                            SeatCapacity = 44,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            BusManufacturerId = 5,
                            HasToilet = false,
                            Name = "Travego",
                            SeatCapacity = 44,
                            Type = 2
                        });
                });

            modelBuilder.Entity("GoxuTour.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kastamonu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sakarya"
                        });
                });

            modelBuilder.Entity("GoxuTour.Domain.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Büyük İstanbul Otogari"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Alibeyköy"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Aşti"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Name = "Terminal"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "Terminal"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            Name = "Terminal"
                        });
                });

            modelBuilder.Entity("GoxuTour.Domain.Bus", b =>
                {
                    b.HasOne("GoxuTour.Domain.BusModel", "BusModel")
                        .WithMany()
                        .HasForeignKey("BusModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusModel");
                });

            modelBuilder.Entity("GoxuTour.Domain.BusModel", b =>
                {
                    b.HasOne("GoxuTour.Domain.BusManufacturer", "BusManufacturer")
                        .WithMany()
                        .HasForeignKey("BusManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusManufacturer");
                });

            modelBuilder.Entity("GoxuTour.Domain.Station", b =>
                {
                    b.HasOne("GoxuTour.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
